cloud:
  aws:
    credentials:
      access-key: AKIASW4IIXSQQZODEL44
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: javatechieproject


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
